# Generated by Django 5.1.6 on 2025-04-23 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adam', '0003_remove_artist_tasks_task_artist_checkinresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinresponse',
            name='user',
        ),
        migrations.AddField(
            model_name='checkinresponse',
            name='artist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adam.artist'),
            preserve_default=False,
        ),
    ]
