# Generated by Django 5.1.6 on 2025-04-23 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adam', '0005_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='adam.artist'),
        ),
    ]
