# Generated by Django 5.1.6 on 2025-04-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adam', '0006_alter_task_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinresponse',
            name='session_key',
            field=models.CharField(db_index=True, default=None, max_length=40),
            preserve_default=False,
        ),
    ]
